import type { WPPost } from '@/lib/wordpress';

export const BLOG_FALLBACK_POSTS: WPPost[] = [
  {
    id: 1,
    slug: 'gps-guard-tracking-guide',
    date: '2025-05-14',
    modified: '2025-05-14',
    title: { rendered: 'GPS Guard Tracking: The Complete Guide' },
    excerpt: { rendered: '<p>Real-time GPS tracking is transforming how security companies manage their guards. Here\'s everything you need to know.</p>' },
    content: { rendered: `<p>GPS guard tracking gives supervisors live visibility into where guards are, where they have been, and whether shifts are being completed on time.</p><h2>Why it matters</h2><p>For mobile patrol teams, location data reduces blind spots, improves client reporting, and makes incident response faster.</p>` },
    featured_media: 0,
    categories: [1],
    tags: [],
    acf: {},
  },
  {
    id: 2,
    slug: 'nfc-checkpoints-patrol-fraud',
    date: '2025-05-07',
    modified: '2025-05-07',
    title: { rendered: 'How NFC Checkpoints Eliminate Patrol Fraud and Build Client Trust' },
    excerpt: { rendered: '<p>Patrol fraud costs security companies millions in liability and lost contracts each year. NFC checkpoints end it.</p>' },
    content: { rendered: `<p>NFC checkpoints create verifiable proof that a guard physically visited a location at the expected time.</p><p>This closes the gap between what was scheduled and what was actually completed.</p>` },
    featured_media: 0,
    categories: [2],
    tags: [],
    acf: {},
  },
  {
    id: 3,
    slug: 'security-licence-compliance',
    date: '2025-04-28',
    modified: '2025-04-28',
    title: { rendered: 'Security Guard Licence Compliance: A Manager\'s Guide' },
    excerpt: { rendered: '<p>Managing security licence compliance across a large guard workforce is complex. This guide covers everything managers need to know.</p>' },
    content: { rendered: `<p>Licence compliance is one of the highest-risk parts of guard scheduling.</p><p>A system should block expired licences, surface upcoming renewals, and keep a full audit trail.</p>` },
    featured_media: 0,
    categories: [3],
    tags: [],
    acf: {},
  },
  {
    id: 4,
    slug: 'ditching-spreadsheets-2025',
    date: '2025-04-18',
    modified: '2025-04-18',
    title: { rendered: 'Why Security Companies Are Ditching Spreadsheets in 2025' },
    excerpt: { rendered: '<p>A survey of 200 security operations managers reveals the real cost of running on spreadsheets — and what forward-thinking companies are doing instead.</p>' },
    content: { rendered: `<p>Spreadsheets break down quickly once you manage multiple sites, rotating shifts, and compliance deadlines.</p><p>Dedicated operations software reduces admin work and lowers the risk of costly mistakes.</p>` },
    featured_media: 0,
    categories: [1],
    tags: [],
    acf: {},
  },
  {
    id: 5,
    slug: 'lone-worker-safety',
    date: '2025-04-08',
    modified: '2025-04-08',
    title: { rendered: 'The Lone Worker Safety Handbook' },
    excerpt: { rendered: '<p>Lone workers in the security industry face unique risks. This handbook covers best practices, legal obligations and the technology solutions that keep guards safe.</p>' },
    content: { rendered: `<p>Lone workers need dependable check-ins, SOS escalation, and clear location visibility.</p><p>Safety tools should be fast to use and reliable in the field.</p>` },
    featured_media: 0,
    categories: [2],
    tags: [],
    acf: {},
  },
  {
    id: 6,
    slug: 'patrolpilot-vs-guardhouse',
    date: '2025-03-25',
    modified: '2025-03-25',
    title: { rendered: 'PatrolPilot vs Guardhouse: Which Security Management Software Is Right for You?' },
    excerpt: { rendered: '<p>A detailed, honest comparison for security companies — features, pricing, compliance and customer support.</p>' },
    content: { rendered: `<p>Choosing the right platform comes down to scheduling, reporting, guard app usability, and support quality.</p><p>This comparison helps teams evaluate which system better fits their operations.</p>` },
    featured_media: 0,
    categories: [3],
    tags: [],
    acf: {},
  },
];
